# Generated by Django 4.0.5 on 2023-10-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_comments_count_comment_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
